name: Build Kernel Pissarro
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/pissarro-development/android_kernel_xiaomi_pissarro-hydrogen.git kernel_source

      - name: Check Files
        run: |
          echo "Kernel source cloned successfully!"
          ls -la kernel_source
          
