name: Build Kernel Pissarro
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Environment
        run: |
          echo "Environment is ready for building!"
          
